os:
- linux
language: node_js
node_js:
- '7'
- '6'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- openssl aes-256-cbc -K $encrypted_d6da8abbdec3_key -iv $encrypted_d6da8abbdec3_iv
  -in travis.tar.enc -out travis.tar -d
install:
- tar xvf travis.tar
- yarn
script:
- yarn run lint
- yarn run mocha
